# IMPORT LIBRARIES & DATASET

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:

fraud_df = pd.read_csv("../input/creditcardfraud/creditcard.csv")
fraud_df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

# DATA ANALYSIS

In [3]:
#What is the size of the data set?
print(f"Dataset Shape :\n{fraud_df.shape}")

Dataset Shape :
(284807, 31)


In [4]:
#How many features does the data set have?
print(f"Columns or Feature names : \n {fraud_df.columns}")

Columns or Feature names : 
 Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')


In [5]:
#  What are the target values?
print(f"Unique values of target variable : \n {fraud_df['Class'].unique()}")

Unique values of target variable : 
 [0 1]


In [6]:
# How many samples below each target value?
print(f"Number of samples under each target value : \n {fraud_df['Class'].value_counts()}")

Number of samples under each target value : 
 0    284315
1       492
Name: Class, dtype: int64


# DATA Preprocessing

In [7]:
# remove irrelevant features
fraud_df = fraud_df.drop(['Time'], axis=1)
print(f"list of feature names after removing Time column : \n{fraud_df.columns}")

list of feature names after removing Time column : 
Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount', 'Class'],
      dtype='object')


In [8]:
fraud_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 30 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   V1      284807 non-null  float64
 1   V2      284807 non-null  float64
 2   V3      284807 non-null  float64
 3   V4      284807 non-null  float64
 4   V5      284807 non-null  float64
 5   V6      284807 non-null  float64
 6   V7      284807 non-null  float64
 7   V8      284807 non-null  float64
 8   V9      284807 non-null  float64
 9   V10     284807 non-null  float64
 10  V11     284807 non-null  float64
 11  V12     284807 non-null  float64
 12  V13     284807 non-null  float64
 13  V14     284807 non-null  float64
 14  V15     284807 non-null  float64
 15  V16     284807 non-null  float64
 16  V17     284807 non-null  float64
 17  V18     284807 non-null  float64
 18  V19     284807 non-null  float64
 19  V20     284807 non-null  float64
 20  V21     284807 non-null  float64
 21  V22     28

# Data transformation

In [9]:
print(f"few values of Amount column: \n {fraud_df['Amount'][0:4]}")

few values of Amount column: 
 0    149.62
1      2.69
2    378.66
3    123.50
Name: Amount, dtype: float64


In [10]:
#We will change the values to a smaller range. 
fraud_df['norm_amount'] = StandardScaler().fit_transform(
fraud_df['Amount'].values.reshape(-1,1))
fraud_df = fraud_df.drop(['Amount'], axis=1)
print(f"Amount column after applying StandardScaler: \n {fraud_df['norm_amount'][0:4]}")

Amount column after applying StandardScaler: 
 0    0.244964
1   -0.342475
2    1.160686
3    0.140534
Name: norm_amount, dtype: float64


In [11]:
#Features and target creations
X = fraud_df.drop(['Class'], axis=1)
y = fraud_df[['Class']]

In [12]:
#splitting dataset to train & test dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(199364, 29)
(85443, 29)
(199364, 1)
(85443, 1)


In [13]:
#Building decision tree

def decision_tree_classification(X_train, y_train, X_test, y_test):
    dt_classifier = DecisionTreeClassifier()
    print("Model training starts........")
    dt_classifier.fit(X_train, y_train.values.ravel())
    print("Model training completed")
    acc_score = dt_classifier.score(X_test, y_test)
    print(f'Accuracy of model on test dataset :- {acc_score}')
    y_pred = dt_classifier.predict(X_test)
    #confusion matrix
    print(f"Confusion Matrix :- \n {confusion_matrix(y_test, y_pred)}")
    print(f"Classification Report :- \n {classification_report(y_test, y_pred)}")
    
decision_tree_classification(X_train, y_train, X_test, y_test)

Model training starts........
Model training completed
Accuracy of model on test dataset :- 0.9992158515033414
Confusion Matrix :- 
 [[85266    30]
 [   37   110]]
Classification Report :- 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.79      0.75      0.77       147

    accuracy                           1.00     85443
   macro avg       0.89      0.87      0.88     85443
weighted avg       1.00      1.00      1.00     85443



In [14]:
#Model with randomforest

def random_forest_classifier(X_train, y_train, X_test, y_test):
    rt_classifier = RandomForestClassifier(n_estimators=50)
    print("Model training starts........")
    rt_classifier.fit(X_train, y_train.values.ravel())
    acc_score = rt_classifier.score(X_test, y_test)
    print(f'Accuracy of model on test dataset :- {acc_score}')
    y_pred = rt_classifier.predict(X_test)
    #Confusion Matrix
    print(f"Confusion Matrix :- \n {confusion_matrix(y_test, y_pred)}")
    print(f"Classification Report :- \n {classification_report(y_test, y_pred)}")
    
decision_tree_classification(X_train, y_train, X_test, y_test)

Model training starts........
Model training completed
Accuracy of model on test dataset :- 0.9992275552122467
Confusion Matrix :- 
 [[85268    28]
 [   38   109]]
Classification Report :- 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.80      0.74      0.77       147

    accuracy                           1.00     85443
   macro avg       0.90      0.87      0.88     85443
weighted avg       1.00      1.00      1.00     85443



In [15]:
#Target class distribution

class_val = fraud_df['Class'].value_counts()
print(f"Number of samples for each class :- \n {class_val}")
non_fraud = class_val[0]
fraud = class_val[1]
print(f"Non Fraudulent Numbers :- {non_fraud}")
print(f"Fraudulent Numbers :- {fraud}")

Number of samples for each class :- 
 0    284315
1       492
Name: Class, dtype: int64
Non Fraudulent Numbers :- 284315
Fraudulent Numbers :- 492


In [16]:
#take indexes of non fraudulent
nonfraud_indexies = fraud_df[fraud_df.Class == 0].index
fraud_indices = np.array(fraud_df[fraud_df['Class'] == 1].index)
#take random samples from non fraudulent that are equal to fraudulent samples
random_normal_indexies = np.random.choice(nonfraud_indexies, fraud, replace=False)
random_normal_indexies = np.array(random_normal_indexies)

In [17]:
## Undersampling techniques

# concatenate both indices of fraud and non fraud
under_sample_indices = np.concatenate([fraud_indices, random_normal_indexies])

#extract all features from whole data for under sample indices only
under_sample_data = fraud_df.iloc[under_sample_indices, :]

# now we have to divide under sampling data to all features & target
x_undersample_data = under_sample_data.drop(['Class'], axis=1)
y_undersample_data = under_sample_data[['Class']]
# now split dataset to train and test datasets as before
X_train_sample, X_test_sample, y_train_sample, y_test_sample = train_test_split(
x_undersample_data, y_undersample_data, test_size=0.2, random_state=0)

In [18]:
#Building decision tree

def decision_tree_classification(X_train, y_train, X_test, y_test):
    dt_classifier = DecisionTreeClassifier()
    print("Model training starts........")
    dt_classifier.fit(X_train, y_train.values.ravel())
    print("Model training completed")
    acc_score = dt_classifier.score(X_test, y_test)
    print(f'Accuracy of model on test dataset :- {acc_score}')
    y_pred = dt_classifier.predict(X_test)
    #confusion matrix
    print(f"Confusion Matrix :- \n {confusion_matrix(y_test, y_pred)}")
    print(f"Classification Report :- \n {classification_report(y_test, y_pred)}")
    
decision_tree_classification(X_train_sample, y_train_sample, 
X_test_sample, y_test_sample)

Model training starts........
Model training completed
Accuracy of model on test dataset :- 0.9035532994923858
Confusion Matrix :- 
 [[93 13]
 [ 6 85]]
Classification Report :- 
               precision    recall  f1-score   support

           0       0.94      0.88      0.91       106
           1       0.87      0.93      0.90        91

    accuracy                           0.90       197
   macro avg       0.90      0.91      0.90       197
weighted avg       0.91      0.90      0.90       197



In [19]:
#Model with randomforest

def random_forest_classifier(X_train, y_train, X_test, y_test):
    rt_classifier = RandomForestClassifier(n_estimators=50)
    print("Model training starts........")
    rt_classifier.fit(X_train, y_train.values.ravel())
    acc_score = rt_classifier.score(X_test, y_test)
    print(f'Accuracy of model on test dataset :- {acc_score}')
    y_pred = rt_classifier.predict(X_test)
    #Confusion Matrix
    print(f"Confusion Matrix :- \n {confusion_matrix(y_test, y_pred)}")
    print(f"Classification Report :- \n {classification_report(y_test, y_pred)}")

random_forest_classifier(X_train_sample, y_train_sample, X_test_sample, y_test_sample)

Model training starts........
Accuracy of model on test dataset :- 0.9593908629441624
Confusion Matrix :- 
 [[102   4]
 [  4  87]]
Classification Report :- 
               precision    recall  f1-score   support

           0       0.96      0.96      0.96       106
           1       0.96      0.96      0.96        91

    accuracy                           0.96       197
   macro avg       0.96      0.96      0.96       197
weighted avg       0.96      0.96      0.96       197

